6 implementiere rudimentäres datenmodell für components
jqassistant-plugin/jqassistant-openapi-plugin pull request #22
Opened 2023-06-21 00:02 UTC by UzeyirMammadov

As the child nodes of the component are not yet implemented, it is not possible to write tests.

2023-06-21 13:58 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/ContractDescriptor.java
> +    ComponentDescriptor getComponents();
should not work as implemented. 
in my understanding a contract can define multiple components, current implementation allows only one.
working solution could use list of type `componentDescriptor`

2023-06-21 14:01 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/ComponentDescriptor.java
> +@Label("Components")
label describes the node - singular needed - "Component" without `s`

2023-06-21 14:04 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/ExampleDescriptor.java
> +@Label("Examples")
label describes the node - singular needed

2023-06-21 14:04 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/LinkDescriptor.java
> +@Label("Links")
label describes the node - singular needed

2023-06-21 14:08 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/SchemaDescriptor.java
> +@Label("Schemas")
label describes the node - singular needed

2023-06-21 14:08 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/SecuritySchemaDescriptor.java
> +@Label("SecuritySchemas")
label describes the node - singular needed

2023-06-21 14:22 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/CallbackDescriptor.java
> +@Label("Callbacks")
label describes the node - singular needed

2023-06-21 14:29 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/ComponentDescriptor.java
we should discuss the relation between these components and the actual contract.

ideas: 
- node to unite all components necessary?
- create ComponentDescriptor as parent for all components to be able to differentiate between e.g. used RequestBody and unused RequestBody as component via "component" label

2023-06-21 14:29 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/ComponentDescriptor.java
@jp06upel @LukRnix

2023-06-21 14:32 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/OpenAPIScannerPlugin.java
> +    ComponentDescriptor parseComponent(Components components, Store store) {
function parses multiple components --> name should be accordingly `parseComponents`

2023-06-21 14:36 UTC, jp06upel commented on src/main/java/org/jqassistant/plugin/openapi/api/model/ComponentDescriptor.java
I think the model is right but has singular / plural mixed up.
I do think a component (currently Component) node is useful. But the other nodes shouldnt have group nodes. 
maybe we should discuss this in person. @CodeOfRob

2023-06-21 14:40 UTC, CodeOfRob requested changes
- good implementation of scanning
- Descriptors need some changes (see comments)
- some code smells to remove

2023-06-21 17:09 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/api/model/PathItemDescriptor.java
But components node has a link to PathItem. Should it be linked with Path then?

2023-06-21 17:10 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/PathItemDescriptor.java
yes, that should work

2023-06-21 18:23 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/api/model/PathItemDescriptor.java
Should parseComponents then read all paths in the scanner class instead of PathItems? If so, is that the right way? The component in the OpeanAPI doc has no fixed field "Path".

2023-06-21 18:27 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/api/model/PathItemDescriptor.java
I think we still need this descriptor.

2023-06-21 18:45 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/PathItemDescriptor.java
try the following:

instead the current implementation in the scanner:
`if (components.getPathItems() != null && !components.getPathItems().isEmpty()) {
            List<PathItemDescriptor> pathItemDescriptors = new ArrayList<>();
            for (PathItem pathItem : components.getPathItems().values()) {
                pathItemDescriptors.add(parsePathItems(pathItem, store));
            }
            componentDescriptor.getPathItems().addAll(pathItemDescriptors);
}`

use this:
`if (components.getPathItems() != null && !components.getPathItems().isEmpty()) {
            componentDescriptor.getPaths().addAll(parsePaths(components.getPathItems());
}`

`parsePaths` should return a list of type `PathDescriptor` so you would also need to update the pathItems field in `ComponentDescriptor` to the type `List<PathDescriptor>` and rename the getter method to `getPaths()`

let me know if further clarification or discussion is needed

2023-06-21 18:47 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/PathItemDescriptor.java
the function `parsePaths` and the `pathDescriptor` should already exist

2023-06-21 19:05 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/api/model/PathItemDescriptor.java
`parsePaths` requires a parameter of type Paths but `getPathItems` provides `Map<java.lang.String,io.swagger.v3.oas.models.PathItem>`

2023-06-21 19:08 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/api/model/PathItemDescriptor.java
Resolved it

2023-06-21 19:26 UTC, UzeyirMammadov commented on src/test/java/org/jqassistant/plugin/openapi/parser/ComponentsTest.java
Thinking of adding some tests in it rn :)

2023-06-22 07:42 UTC, jp06upel commented on src/main/java/org/jqassistant/plugin/openapi/impl/ComponentElementReader.java
> +    private final OpenAPIScannerPlugin openAPIScannerPlugin;
A static class could also be an option here. If not: maybe also add the Store, ComponensDescriptor and Components to the constructor. That way the method signature is smaller.

2023-06-22 07:43 UTC, jp06upel commented on src/main/java/org/jqassistant/plugin/openapi/impl/ComponentElementReader.java
> +    private final OpenAPIScannerPlugin openAPIScannerPlugin;
note: that could be part of another ticket already in our todos.

2023-06-22 13:52 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/ComponentDescriptor.java
TODO: check if parser adds "inline" components to overall components node

discussed:
- no component label
- components node to hold all children

2023-06-24 11:52 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/api/model/ComponentDescriptor.java
Should it be done in tests? If not, what should happen if inline components are not added?

2023-06-24 12:24 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/ComponentDescriptor.java
the part including checking for "inline components" is not now defined in another ticket from @LukRnix and not relevant anymore.

componentsdescriptor as parent node for all componentDescriptors is already implemented i believe.
.... seems like this convo is resolved..

2023-06-24 12:28 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/ComponentDescriptor.java
> +public interface ComponentDescriptor extends OpenApiDescriptor {
since this class represents a descriptor holding all components label should be plural "Components" and accordingly class should be named "ComponentsDescriptor"

2023-06-24 12:32 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/impl/ComponentElementReader.java
> +    private final OpenAPIScannerPlugin openAPIScannerPlugin;
Think it would be better to make it part of other ticket.

2023-06-24 12:33 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/ComponentElementReader.java
> +    private final OpenAPIScannerPlugin openAPIScannerPlugin;
to prevent confusion and merge conflicts I would plead to revert the splitting of scannerClass on this branch and use separate branch with according issue for that

2023-06-24 12:34 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/ComponentElementReader.java
> +    private final OpenAPIScannerPlugin openAPIScannerPlugin;
see #26

2023-06-24 12:42 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/impl/ComponentElementReader.java
> +    private final OpenAPIScannerPlugin openAPIScannerPlugin;
Are there any potential merge Conflicts? If not I would suggest to merge it this way bcs pretty lot things should be reverted then.

2023-06-24 12:44 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/impl/ComponentElementReader.java
> +    private final OpenAPIScannerPlugin openAPIScannerPlugin;
We can use #26 to refine the splitting

2023-06-24 12:49 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/ComponentElementReader.java
> +    private final OpenAPIScannerPlugin openAPIScannerPlugin;
yes but current split is not quite on the quality level for main branch in my opinion and finishing the split to reach that level would take a big enough amount of time to define an extra ticket for that (already done #26).

i would rather take the effort to revert the split in this ticket and to do it clean in another one than to merge incomplete splits into main.

opinions? @jp06upel @LukRnix

2023-06-24 12:56 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/impl/ComponentElementReader.java
> +    private final OpenAPIScannerPlugin openAPIScannerPlugin;
There are things to refine, but I wouldn't say they're so incomplete that they can't be merged. Also, it's not such a big change, split classes are only used in two methods. And as you said, splitting can take a large amount of time, so it would be useful to have this split as a basis for the next ticket to reduce the amount of time that would be spent on it.

2023-06-24 13:13 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/ComponentsDescriptor.java
> +public interface ComponentsDescriptor extends OpenApiDescriptor {
now 
```java
@Label("Components")
```
 is missing xD

2023-06-24 13:14 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/impl/ComponentElementReader.java
> +    private final OpenAPIScannerPlugin openAPIScannerPlugin;
P.S the classes were splitted bcs of code smells in SonarQube

2023-06-24 13:17 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/ComponentElementReader.java
> +    private final OpenAPIScannerPlugin openAPIScannerPlugin;
right...

if the others (especially @LukRnix since he is assigned to the splitting ticket) are fine with merge, I'm ok with merging too

2023-06-24 13:17 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/api/model/ComponentsDescriptor.java
> +public interface ComponentsDescriptor extends OpenApiDescriptor {
I saw in TODOs "no component label". Did I get it wrong?

2023-06-24 13:21 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/ComponentsDescriptor.java
> +public interface ComponentsDescriptor extends OpenApiDescriptor {
ah my bad. bad communication.

that was meant to say that there shouldnt be a label "component" on the actual component nodes (like requestBody) to indicate that those are defined under the components section in contract.
we still need the label "components" on the ComponentsDescriptor.

sorry for that 🙈

2023-06-24 13:23 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/ComponentElementReader.java
> +    private final OpenAPIScannerPlugin openAPIScannerPlugin;
resolved due to majority for merging and refactoring in #26.

2023-06-25 11:07 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/OpenAPIScannerPlugin.java
> +    SchemaDescriptor parseSchemas(Schema schema, Store store){
only one schema object gets parsed --> function should be named "parseSchema"

(slowly beginning to feel a bit petty xD. Do I care about these things to much?)

2023-06-25 11:13 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/api/model/ComponentsDescriptor.java
> +public interface ComponentsDescriptor extends OpenApiDescriptor {
since node holds multiple components and class is named `ComponentsDescriptor` label also needs an "s" at the end --> "Components"

2023-06-25 11:16 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/impl/OpenAPIScannerPlugin.java
> +    SchemaDescriptor parseSchemas(Schema schema, Store store){
You are right to do so, the naming should be correct.

2023-06-25 18:52 UTC, CodeOfRob approved these changes
code looks nice now
impressive work
🥳

2023-06-25 21:58 UTC, CodeOfRob approved these changes

2023-06-26 09:11 UTC, merged