35 modify paths handling
jqassistant-plugin/jqassistant-openapi-plugin pull request #36
Opened 2023-07-26 09:39 UTC by CodeOfRob

closes #35

2023-07-26 09:43 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/parsers/PathsParser.java
> +            if (pathItemEntry.getValue() == null){ // happens if empty $ref property is defined in path
@ Reviews
should we skip parsing of faulty objects (current implementation) or should we return a descriptor with only the name and no relations whatsoever

2023-07-26 21:04 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/impl/parsers/PathsParser.java
> +            if (pathItemEntry.getValue() == null){ // happens if empty $ref property is defined in path
by returning a descriptor you mean to still add it to the list with only a name?

2023-07-26 21:06 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/parsers/PathsParser.java
> +            if (pathItemEntry.getValue() == null){ // happens if empty $ref property is defined in path
yes

2023-07-26 21:17 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/impl/parsers/PathsParser.java
> +            if (pathItemEntry.getValue() == null){ // happens if empty $ref property is defined in path
If the handling of faulty objects are not causing any problems in downstream then imo it would be better to return a descriptor. This way we can still preserve some info about the faulty objects and the output will be more consistent.

2023-07-27 10:17 UTC, jp06upel approved these changes
looking good

2023-07-28 12:07 UTC, jp06upel requested changes

2023-07-28 12:07 UTC, jp06upel commented on src/main/java/org/jqassistant/plugin/openapi/impl/parsers/PathsParser.java
> +            if (pathItemEntry.getValue() == null){ // happens if empty $ref property is defined in path
Info from meeting:
Adding a empty ref Node is preferred. Also: The error message should be a warning  or none.

2023-07-31 11:13 UTC, jp06upel commented on src/main/java/org/jqassistant/plugin/openapi/impl/parsers/PathsParser.java
> +            pathItemDescriptor.setPathUrl(pathUrl);
here is a tiny bit of code duplication, you allready got the setProperties function with null guards, why dont you use it and the the null check later on and return early from there? (basicly move the setProperties before this null check, and remove the setPathurl call)

2023-07-31 11:23 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/parsers/PathsParser.java
> +            pathItemDescriptor.setPathUrl(pathUrl);
setProperties doesn't null guard against the pathItem being null itself I think, which is the case the warning should appear.
removed path property setter from setProperties and moved before the null check. should eliminate duplication too

2023-07-31 11:30 UTC, merged