41 json implement discriminator logic
jqassistant-plugin/jqassistant-openapi-plugin pull request #67
Opened 2023-08-08 13:18 UTC by jp06upel

closes #41

2023-08-08 13:41 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
if schema already exists, is the rest of this function necessary (just overwrites the existing schema with same schema isnt it) ?

2023-08-08 13:43 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +        } else {
empty checks are already done by the for loops i think. so in theory we can lose these and decrease the count of edge cases which need to be covered by tests

2023-08-08 13:50 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +    private DiscriminatorDescriptor parseDiscriminator(Schema<?> schema) {
passing of whole schema could be reduced to passing only discriminator object

2023-08-08 13:51 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +        if (schema.getDiscriminator().getMapping() != null && !schema.getDiscriminator().getMapping().isEmpty()) {
explicit empty check needed?

2023-08-08 13:59 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +            for (Schema x : schema.getAllOf()){
loop over `schema.getAllOf` intended or should we rather loop over `schema.getOneOf`?

2023-08-08 13:59 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +            for (Schema x : schema.getAllOf()){
loop over `schema.getAllOf` intended or should we rather loop over `schema.getAnyOf`?

2023-08-08 14:07 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +                return parseNull(property); // No Type present
could pull return one indentation to the left and lose the else (no idea if that is better or worse)

2023-08-08 14:11 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +                throw new UnknownTypeException("Unknown Type \"" + property.getType() + "\"");
Didn't we want to create a descriptor of unknown type and throw warning?

2023-08-08 14:18 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +        }
could lose the brackets

2023-08-08 14:32 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +    private TypeDescriptor parseXof(Schema x){
maybe choose a more speaking name than "x"

2023-08-08 14:37 UTC, CodeOfRob commented on src/test/java/org/jqassistant/plugin/openapi/parser/JsonSchemaTest.java
test coverage looks good, would wish additional coverage of `schema.getOneOf`and schema.getAnyOf`.

am skipping detailed review of the tests and trusting sonars analysis

2023-08-08 14:38 UTC, CodeOfRob requested changes
looks really good, i think i found some small mistakes. pls take a look at my comments

2023-08-09 08:40 UTC, jp06upel commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
yes this function always parses/overwrites! to get a reference, you should use the ResolverClass.

2023-08-09 08:41 UTC, jp06upel commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +            for (Schema x : schema.getAllOf()){
woops copy pasta hit again xD

2023-08-09 08:43 UTC, jp06upel commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +        } else {
i dont quite get what you mean here.

2023-08-09 08:46 UTC, jp06upel commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +                throw new UnknownTypeException("Unknown Type \"" + property.getType() + "\"");
yep but i would like to create a new ticket for this.

2023-08-09 09:19 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +                throw new UnknownTypeException("Unknown Type \"" + property.getType() + "\"");
> yep but i would like to create a new ticket for this.

Agree, it's out of scope if this ticket

2023-08-09 09:31 UTC, jp06upel commented on src/main/java/org/jqassistant/plugin/openapi/impl/parsers/ComponentsParser.java
> +
removed (i dont remember adding this comment)

2023-08-09 11:13 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +        } else {
with every condition you check, a new possible combination of conditions is created, which needs to be tested.

> if( con1 ) --> two possible branches to test
> if( con1 && con2) --> four possible branches to test

by decreasing the condition count you decrease the combinations to test and increase the coverage KPI (with the same tests)

also, a for loop should be able to process empty lists without throwing an error. So the .isEmpty() check is not quite necessary

2023-08-09 11:26 UTC, jp06upel commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +        } else {
got ya!

2023-08-09 11:27 UTC, CodeOfRob commented on src/test/resources/example-jsonschema.yaml
> +      oneOf:
![image](https://github.com/jqassistant-plugin/jqassistant-openapi-plugin/assets/81490319/cda54dce-903e-4cdc-83fd-c09ea6b872dc)

2023-08-09 11:33 UTC, CodeOfRob commented on src/test/java/org/jqassistant/plugin/openapi/parser/JsonSchemaTest.java
> +        List<TypeDescriptor> allOffs = schemaDescriptor.getOneOfSchemas();
![image](https://github.com/jqassistant-plugin/jqassistant-openapi-plugin/assets/81490319/348d35e6-3565-4e82-83f1-4b8bdbe81d62)

2023-08-09 11:53 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +    private NullTypeDescriptor parseNull(final Schema<?> schema){
sonar wants the unused parameter to be removed

2023-08-09 11:53 UTC, CodeOfRob commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +    private BoolTypeDescriptor parseBoolean(final Schema<?> schema){
sonar wants the unused parameter to be removed

2023-08-10 19:00 UTC, UzeyirMammadov commented on src/main/java/org/jqassistant/plugin/openapi/impl/jsonschema/JsonSchemaParser.java
> +    private BoolTypeDescriptor parseBoolean(final Schema<?> schema){
test

2023-08-12 15:08 UTC, CodeOfRob commented on src/test/java/org/jqassistant/plugin/openapi/parser/JsonSchemaTest.java
> +        List<TypeDescriptor> allOffs = schemaDescriptor.getOneOfSchemas();
is this really intended or did you want to `schemaDescriptor.getAnyOfSchemas()` here?

2023-08-13 11:11 UTC, CodeOfRob approved these changes
well done 🥳

2023-08-18 13:21 UTC, CodeOfRob approved these changes

2023-08-18 13:21 UTC, merged